version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: executive_secretariat
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  backend:
    build: 
      context: ./Backend/NestJS
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/executive_secretariat
      - JWT_SECRET=your-jwt-secret-key-change-in-production
      - ENCRYPTION_SECRET_KEY=your-encryption-secret-key-change-in-production
    depends_on:
      - postgres
    networks:
      - app-network

  frontend:
    build: .
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge